#
# RedHat configuration files
#

- name: Install dependencies
  yum: name="bridge-utils" state=present
  tags:
  - bridge
  - el

- name: Create the bridge interface configuration file
  template: src=rh_ifcfg-bridge.j2 dest="{{ rh_network_sysconfig }}/ifcfg-{{ bridge }}"
  tags:
  - bridge
  - el
  when:
  - apply

- name: Create the slave bridge configuration file
  template: src=rh_ifcfg-slave.j2 dest="{{ rh_network_sysconfig }}/ifcfg-{{ item }}" backup=yes
  with_items:
  - "{{ slave }}"
  when:
  - apply
  - "{{ slave|length }}" == 1
  tags:
  - bridge
  - el

- name: Create the bridge interface configuration file
  template: src=rh_ifcfg-bridge.j2 dest="{{ tmp_dir }}/ifcfg-{{ bridge }}"
  tags:
  - bridge
  - el
  when:
  - not apply

- name: Create the slave bridge configuration file
  template: src=rh_ifcfg-slave.j2 dest="{{ tmp_dir }}/ifcfg-{{ item }}" backup=yes
  with_items:
  - "{{ slave }}"
  when:
  - not apply
  - "{{ slave|length }}" == 1
  tags:
  - bridge
  - el
